/* TOKEN */
export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

// BANNER
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILURE = "GET_BANNER_FAILURE";

// DONASI
export const GET_DONASI = "GET_DONASI";
export const GET_DONASI_SUCCESS = "GET_DONASI_SUCCESS";
export const GET_DONASI_FAILURE = "GET_DONASI_FAILURE";

// TENTANG
export const GET_TENTANG = "GET_TENTANG";
export const GET_TENTANG_SUCCESS = "GET_TENTANG_SUCCESS";
export const GET_TENTANG_FAILURE = "GET_TENTANG_FAILURE";

// PROGRAM
export const GET_PROGRAM = "GET_PROGRAM";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_FAILURE = "GET_PROGRAM_FAILURE";