/* TOKEN */
export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

// BANNER
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILURE = "GET_BANNER_FAILURE";

// DONASI
export const GET_DONASI = "GET_DONASI";
export const GET_DONASI_SUCCESS = "GET_DONASI_SUCCESS";
export const GET_DONASI_FAILURE = "GET_DONASI_FAILURE";

// TENTANG
export const GET_TENTANG = "GET_TENTANG";
export const GET_TENTANG_SUCCESS = "GET_TENTANG_SUCCESS";
export const GET_TENTANG_FAILURE = "GET_TENTANG_FAILURE";

// PROGRAM
export const GET_PROGRAM = "GET_PROGRAM";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_FAILURE = "GET_PROGRAM_FAILURE";

// BERITA
export const GET_BERITA = "GET_BERITA";
export const GET_BERITA_SUCCESS = "GET_BERITA_SUCCESS";
export const GET_BERITA_FAILURE = "GET_BERITA_FAILURE";

// PARTNER
export const GET_PARTNER = "GET_PARTNER";
export const GET_PARTNER_SUCCESS = "GET_PARTNER_SUCCESS";
export const GET_PARTNER_FAILURE = "GET_PARTNER_FAILURE";

// ALBUM
export const GET_ALBUM = "GET_ALBUM";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE";

// BENEFICARIES
export const GET_BENEFICARIES = "GET_BENEFICARIES";
export const GET_BENEFICARIES_SUCCESS = "GET_BENEFICARIES_SUCCESS";
export const GET_BENEFICARIES_FAILURE = "GET_BENEFICARIES_FAILURE";

// ACHIEVEMENT
export const GET_ACHIEVEMENT = "GET_ACHIEVEMENT";
export const GET_ACHIEVEMENT_SUCCESS = "GET_ACHIEVEMENT_SUCCESS";
export const GET_ACHIEVEMENT_FAILURE = "GET_ACHIEVEMENT_FAILURE";