/* TOKEN */
export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

// BANNER
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILURE = "GET_BANNER_FAILURE";

// BANNER PROGRAM
export const GET_BANNER_PROGRAM = "GET_BANNER_PROGRAM";
export const GET_BANNER_PROGRAM_SUCCESS = "GET_BANNER_PROGRAM_SUCCESS";
export const GET_BANNER_PROGRAM_FAILURE = "GET_BANNER_PROGRAM_FAILURE";

// DONASI
export const GET_DONASI = "GET_DONASI";
export const GET_DONASI_SUCCESS = "GET_DONASI_SUCCESS";
export const GET_DONASI_FAILURE = "GET_DONASI_FAILURE";

// DONASI
export const GET_DONASI2 = "GET_DONASI2";
export const GET_DONASI2_SUCCESS = "GET_DONASI2_SUCCESS";
export const GET_DONASI2_FAILURE = "GET_DONASI2_FAILURE";

// TENTANG
export const GET_TENTANG = "GET_TENTANG";
export const GET_TENTANG_SUCCESS = "GET_TENTANG_SUCCESS";
export const GET_TENTANG_FAILURE = "GET_TENTANG_FAILURE";

// PROGRAM
export const GET_PROGRAM = "GET_PROGRAM";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_FAILURE = "GET_PROGRAM_FAILURE";
export const GET_PROGRAM_INCIDENTAL_SUCCESS = "GET_PROGRAM_INCIDENTAL_SUCCESS";
export const GET_PROGRAM_INCIDENTAL_FAILURE = "GET_PROGRAM_INCIDENTAL_FAILURE";

// BERITA
export const GET_BERITA = "GET_BERITA";
export const GET_BERITA_SUCCESS = "GET_BERITA_SUCCESS";
export const GET_BERITA_FAILURE = "GET_BERITA_FAILURE";
export const GET_BERITA_BYTAG_SUCCESS = "GET_BERITA_BYTAG_SUCCESS";
export const GET_BERITA_BYTAG_FAILURE = "GET_BERITA_BYTAG_FAILURE";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const GET_TAG_FAILURE = "GET_TAG_FAILURE";
export const GET_HEADLINE_SUCCESS = "GET_HEADLINE_SUCCESS";
export const GET_HEADLINE_FAILURE = "GET_HEADLINE_FAILURE";
export const GET_LOADING = "GET_LOADING"
// PARTNER
export const GET_PARTNER = "GET_PARTNER";
export const GET_PARTNER_SUCCESS = "GET_PARTNER_SUCCESS";
export const GET_PARTNER_FAILURE = "GET_PARTNER_FAILURE";

// ALBUM
export const GET_ALBUM = "GET_ALBUM";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE";

// BENEFICARIES
export const GET_BENEFICARIES = "GET_BENEFICARIES";
export const GET_BENEFICARIES_SUCCESS = "GET_BENEFICARIES_SUCCESS";
export const GET_BENEFICARIES_FAILURE = "GET_BENEFICARIES_FAILURE";
export const GET_BENEFICARIES_ID_SUCCESS = "GET_BENEFICARIES_ID_SUCCESS";
export const GET_BENEFICARIES_ID_FAILURE = "GET_BENEFICARIES_ID_FAILURE";
// ACHIEVEMENT
export const GET_ACHIEVEMENT = "GET_ACHIEVEMENT";
export const GET_ACHIEVEMENT_SUCCESS = "GET_ACHIEVEMENT_SUCCESS";
export const GET_ACHIEVEMENT_FAILURE = "GET_ACHIEVEMENT_FAILURE";

// TESTIMONI
export const GET_TESTIMONI = "GET_TESTIMONI";
export const GET_TESTIMONI_SUCCESS = "GET_TESTIMONI_SUCCESS";
export const GET_TESTIMONI_FAILURE = "GET_TESTIMONI_FAILURE";

// MENU
export const GET_MENU = "GET_MENU";
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_FAILURE = "GET_MENU_FAILURE";

// KONTAK
export const GET_KONTAK = "GET_KONTAK";
export const GET_KONTAK_SUCCESS = "GET_KONTAK_SUCCESS";
export const GET_KONTAK_FAILURE = "GET_KONTAK_FAILURE";

// HUBUNGI
export const GET_HUBUNGI = "GET_HUBUNGI";
export const GET_HUBUNGI_SUCCESS = "GET_HUBUNGI_SUCCESS";
export const GET_HUBUNGI_FAILURE = "GET_HUBUNGI_FAILURE";

// TEAM
export const GET_TEAM = "GET_TEAM";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_FAILURE = "GET_TEAM_FAILURE";

// KATEGORI
export const GET_KATEGORI = "GET_KATEGORI";
export const GET_KATEGORI_SUCCESS = "GET_KATEGORI_SUCCESS";
export const GET_KATEGORI_FAILURE = "GET_KATEGORI_FAILURE";